CREATE TABLE Genre (
	GenreId INT NOT NULL IDENTITY (1, 1),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(50) NULL,
	Notes NVARCHAR(1000) NULL,
	Logo VARBINARY(MAX) NULL,
	CONSTRAINT PK_Genre PRIMARY KEY (GenreId)
)