MERGE INTO Nationality AS target
USING (VALUES
    ('American', 'US'),
    ('Argentinian', 'AR'),
    ('Australian', 'AU'),
    ('Austrian', 'AT'),
    ('Bangladeshi', 'BD'),
    ('Belgian', 'BE'),
    ('Bolivian', 'BO'),
    ('Brazilian', 'BR'),
    ('British', 'GB'),
    ('Bulgarian', 'BG'),
    ('Canadian', 'CA'),
    ('Chilean', 'CL'),
    ('Chinese', 'CN'),
    ('Colombian', 'CO'),
    ('Croatian', 'HR'),
    ('Czech', 'CZ'),
    ('Danish', 'DK'),
    ('Dutch', 'NL'),
    ('Ecuadorian', 'EC'),
    ('Egyptian', 'EG'),
    ('English', 'EN'),
    ('Estonian', 'EE'),
    ('Filipino', 'PH'),
    ('Finnish', 'FI'),
    ('French', 'FR'),
    ('German', 'DE'),
    ('Greek', 'GR'),
    ('Hawaiian', 'HI'),
    ('Hong Kong', 'HK'),
    ('Hungarian', 'HU'),
    ('Icelandic', 'IS'),
    ('Indian', 'IN'),
    ('Indonesian', 'ID'),
    ('Iranian', 'IR'),
    ('Irish', 'IE'),
    ('Israeli', 'IL'),
    ('Italian', 'IT'),
    ('Japanese', 'JP'),
    ('Jordanian', 'JO'),
    ('Kenyan', 'KE'),
    ('Korean', 'KR'),
    ('Latvian', 'LV'),
    ('Lebanese', 'LB'),
    ('Lithuanian', 'LT'),
    ('Malaysian', 'MY'),
    ('Mexican', 'MX'),
    ('Moroccan', 'MA'),
    ('Nepalese', 'NP'),
    ('New Zealander', 'NZ'),
    ('Nigerian', 'NG'),
    ('Norwegian', 'NO'),
    ('Pakistani', 'PK'),
    ('Palestinian', 'PS'),
    ('Peruvian', 'PE'),
    ('Polish', 'PL'),
    ('Portuguese', 'PT'),
    ('Puerto Rican', 'PR'),
    ('Romanian', 'RO'),
    ('Russian', 'RU'),
    ('Saudi Arabian', 'SA'),
    ('Scottish', 'SC'),
    ('Serbian', 'RS'),
    ('Singaporean', 'SG'),
    ('Slovak', 'SK'),
    ('Slovenian', 'SI'),
    ('South African', 'ZA'),
    ('Spanish', 'ES'),
    ('Swedish', 'SE'),
    ('Swiss', 'CH'),
    ('Taiwanese', 'TW'),
    ('Thai', 'TH'),
    ('Turkish', 'TR'),
    ('Ukrainian', 'UA'),
    ('Uruguayan', 'UY'),
    ('Venezuelan', 'VE'),
    ('Vietnamese', 'VN'),
    ('Welsh', 'WL'),
    ('Panamanian', 'PA')
) AS source (Name, IsoCode)
ON target.Name = source.Name
WHEN MATCHED THEN
    UPDATE SET IsoCode = source.IsoCode
WHEN NOT MATCHED THEN
    INSERT (Name, IsoCode)
    VALUES (source.Name, source.IsoCode);
